name: Publish go-admin-doc CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --prod
    - name: Get Path
      run: pwd
    - name: Zip
      run: zip -q -r dist.zip ./docs/.vuepress/dist
    - name: Ls
      run: ls
    - name: 'Copy'
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PORT: ${{ secrets.REMOTE_PORT }}
        SOURCE: ./dist.zip
        TARGET: /data/www/dist/doc/
    - name: mv
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            rm -rf /www/doc
            mv /data/www/dist/doc/dist.zip /www/doc/
            cd /www/doc
            unzip dist.zip
